# Generated by Django 4.0.7 on 2022-09-23 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='is this user active as a Client?', verbose_name='Is client active?')),
                ('token', models.TextField(blank=True, default='', null=True)),
                ('refresh_token', models.TextField(blank=True, default='', null=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('callback_token', models.TextField(blank=True, default='', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
