# Generated by Django 4.0.5 on 2022-10-19 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('string_value', models.TextField(blank=True, null=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('value_type', models.CharField(choices=[('S', 'String'), ('D', 'Decimal'), ('B', 'Boolean'), ('I', 'Integer')], default='S', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='the_clients.client')),
            ],
        ),
    ]
