# Generated by Django 4.0.5 on 2022-10-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_clients', '0002_clientmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmeta',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientmeta',
            name='key',
            field=models.CharField(max_length=50),
        ),
    ]
